[theme]
primaryColor = "#1794F2"
backgroundColor = "#F4F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#102238"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
